name: ci

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --all-extras --dev --frozen
      - name: Run ruff lint
        run: uv run ruff check src tests
      - name: Run ruff format check
        run: uv run ruff format --check src tests
      - name: Run mypy
        run: uv run mypy
      - name: Run ty
        run: uv run ty check
      - name: Run bandit
        run: uv run bandit -r src
      - name: Test with pytest
        run: uv run pytest tests --cov=src
      - name: Minimize uv cache
        run: uv cache prune --ci

  build:
    needs: lint-and-test
    env:
      UV_CACHE_DIR: /tmp/.uv-cache
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"
      - name: Set up uv
        uses: astral-sh/setup-uv@v8.2.0
        with:
          enable-cache: true
          version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --all-extras --dev --frozen
      - name: Build a wheel
        run: uv build
      - name: Minimize uv cache
        run: uv cache prune --ci

  build-image:
    needs: lint-and-test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout source code
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4
      - name: Build docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: false
